export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_AUTH_REQUEST = 'USER_AUTH_REQUEST'
export const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS'
export const USER_AUTH_FAIL = 'USER_AUTH_FAIL'

export const LIST_ADD_REQUEST = 'LIST_ADD_REQUEST'
export const LIST_ADD_SUCCESS = 'LIST_ADD_SUCCESS'
export const LIST_ADD_FAIL = 'LIST_ADD_FAIL'
export const LIST_REMOVE = 'LIST_REMOVE'
export const LIST_UPDATE_REQUEST = 'LIST_UPDATE_REQUEST'
export const LIST_UPDATE_SUCCESS = 'LIST_UPDATE_SUCCESS'
export const LIST_UPDATE_FAIL = 'LIST_UPDATE_FAIL'
export const LISTS_GET_REQUEST = 'LISTS_GET_REQUEST'
export const LISTS_GET_SUCCESS = 'LISTS_GET_SUCCESS'
export const LISTS_GET_FAIL = 'LISTS_GET_FAIL'

export const LISTS_CLEAR_STATE = 'LISTS_CLEAR_STATE'
